# Build stage
FROM node:20 AS build
WORKDIR /app
COPY frontend /app

# Run stage
FROM httpd:2.4
RUN mkdir -p /var/run/apache2 && chown www-data:www-data /var/run/apache2
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_PID_FILE /var/run/apache2/httpd.pid
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./ports.conf /usr/local/apache2/ports.conf
COPY --from=build /app/* /usr/local/apache2/htdocs/